# pull the base image
FROM node:alpine

# set the working direction
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH
ENV NODE_OPTIONS=--openssl-legacy-provider
#NEXT JS build args

ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_DATABASEURL
ARG NEXT_PUBLIC_FIREBASE_PROJECTID
ARG NEXT_PUBLIC_FIREBASE_STORAGEBUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGESENDERID
ARG NEXT_PUBLIC_FIREBASE_APPID
ARG NEXT_PUBLIC_GOOGLE_CALENDARID_CONTIBUS
ARG NEXT_PUBLIC_GOOGLE_CALENDARID_UNNEPNAPOK
ARG NEXT_PUBLIC_GOOGLE_CALENDARKEY
ARG NEXT_PUBLIC_GOOGLE_MAPSKEY
ARG NEXT_PUBLIC_GOOGLE_GAID
ARG NEXT_PUBLIC_CONTENTFUL_SPACEID
ARG NEXT_PUBLIC_CONTENTFUL_ACCESTOKEN
ARG NEXT_PUBLIC_SENDGRID_USER
ARG NEXT_PUBLIC_SENDGRID_PASS

# install app dependencies
COPY package.json ./
COPY yarn.lock ./
RUN yarn install --production

# add app
COPY . ./
RUN yarn run build
EXPOSE 8084

# start app
CMD ["yarn", "start"]